package lonestarrr.arconia.client.integration.jei;

import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.vertex.PoseStack;
import lonestarrr.arconia.common.Arconia;
import lonestarrr.arconia.common.block.ModBlocks;
import mezz.jei.api.constants.VanillaTypes;
import mezz.jei.api.gui.builder.IRecipeLayoutBuilder;
import mezz.jei.api.gui.drawable.IDrawable;
import mezz.jei.api.gui.ingredient.IRecipeSlotsView;
import mezz.jei.api.helpers.IGuiHelper;
import mezz.jei.api.recipe.IFocusGroup;
import mezz.jei.api.recipe.RecipeIngredientRole;
import mezz.jei.api.recipe.RecipeType;
import mezz.jei.api.recipe.category.IRecipeCategory;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;

import javax.annotation.Nonnull;

/** Virtual recipe category for showing all items that are generated by the pot of gold
 */
public class EnchantedRootRecipeCategory implements IRecipeCategory<EnchantedRootRecipe> {
    private final IDrawable background;
    private final IDrawable overlay;
    private final IDrawable icon;
    private final ItemStack renderStack = new ItemStack(ModBlocks.hat.get().asItem());

    public static final RecipeType<EnchantedRootRecipe> TYPE =
            RecipeType.create(Arconia.MOD_ID, "enchanted_root", EnchantedRootRecipe.class);

    public EnchantedRootRecipeCategory(@Nonnull IGuiHelper guiHelper) {
        this.background = guiHelper.createBlankDrawable(144, 81);
        this.overlay = guiHelper.createDrawable(new ResourceLocation(Arconia.MOD_ID, "textures/gui/jei/enchanted_root_overlay.png"),
                0, 0, 144, 81);
        this.icon = guiHelper.createDrawableIngredient(VanillaTypes.ITEM_STACK, renderStack.copy());
    }
    @Override
    public RecipeType<EnchantedRootRecipe> getRecipeType() {
        return TYPE;
    }

    @Override
    public Component getTitle() {
        return Component.translatable("jei.arconia.recipe_category.enchanted_root");
    }

    @Override
    public IDrawable getBackground() {
        return this.overlay;
    }

    @Override
    public IDrawable getIcon() {
        return this.icon;
    }

    @Override
    public void draw(EnchantedRootRecipe recipe, IRecipeSlotsView recipeSlotsView, GuiGraphics gui, double mouseX, double mouseY) {
        RenderSystem.enableBlend();
        overlay.draw(gui, 0, 0);
        RenderSystem.disableBlend();

    }

    @Override
    public void setRecipe(IRecipeLayoutBuilder builder, EnchantedRootRecipe recipe, IFocusGroup focuses) {
        ItemStack root = recipe.getColoredRoot();
        ItemStack generated = recipe.getOutput();
        builder.addSlot(RecipeIngredientRole.INPUT, 33, 33).addItemStack(root);
        builder.addSlot(RecipeIngredientRole.OUTPUT, 121, 33).addItemStack(generated);
    }
}
