package lonestarrr.arconia.client.integration.jei;

import lonestarrr.arconia.common.item.ColoredRoot;
import net.minecraft.world.item.ItemStack;

/**
 * Represents a virtual recipe that will show, in JEI, output generated by an enchanted colored root. This will help players discover
 * that items can be generated by the pot of gold.
 */
public class EnchantedRootRecipe {
    ItemStack coloredRoot;

    public EnchantedRootRecipe(ItemStack coloredRoot) {
        this.coloredRoot = coloredRoot;
    }

    public ItemStack getColoredRoot() {
        return this.coloredRoot;
    }

    public ItemStack getOutput() {
        return ColoredRoot.getResourceItem(this.coloredRoot);
    }
}
