package lonestarrr.arconia.client.integration.jei;

import lonestarrr.arconia.common.item.ColoredBranch;
import net.minecraft.world.item.ItemStack;

/**
 * Represents a virtual recipe that will show, in JEI, output generated by an imbued colored branch. This will help players discover
 * that items can be generated by the pot of gold.
 */
public class ImbuedBranchRecipe {
    ItemStack coloredBranch;

    public ImbuedBranchRecipe(ItemStack coloredBranch) {
        this.coloredBranch = coloredBranch;
    }

    public ItemStack getColoredBranch() {
        return this.coloredBranch;
    }

    public ItemStack getOutput() {
        return ColoredBranch.getResourceItem(this.coloredBranch);
    }
}
