package lonestarrr.arconia.client.integration.jei;

import lonestarrr.arconia.common.Arconia;
import lonestarrr.arconia.common.block.ModBlocks;
import lonestarrr.arconia.common.core.RainbowColor;
import lonestarrr.arconia.common.crafting.ModRecipeTypes;
import lonestarrr.arconia.common.crafting.PedestalRecipe;
import lonestarrr.arconia.common.item.ColoredRoot;
import lonestarrr.arconia.common.item.ModItems;
import mezz.jei.api.IModPlugin;
import mezz.jei.api.JeiPlugin;
import mezz.jei.api.registration.IRecipeCatalystRegistration;
import mezz.jei.api.registration.IRecipeCategoryRegistration;
import mezz.jei.api.registration.IRecipeRegistration;
import mezz.jei.api.registration.ISubtypeRegistration;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.crafting.RecipeHolder;

import java.util.ArrayList;
import java.util.List;

@JeiPlugin
public class JEIArconiaPlugin implements IModPlugin {
    private static final ResourceLocation ID = new ResourceLocation(Arconia.MOD_ID, "main");

    @Override
    public ResourceLocation getPluginUid() {
        return ID;
    }

    @Override
    public void registerCategories(IRecipeCategoryRegistration registry) {
        registry.addRecipeCategories(
            new AltarRecipeCategory(registry.getJeiHelpers().getGuiHelper()),
            new EnchantedRootRecipeCategory(registry.getJeiHelpers().getGuiHelper())
        );
    }

    @Override
    public void registerRecipeCatalysts(IRecipeCatalystRegistration registry) {
        // The (main) blocks that process the recipes
        registry.addRecipeCatalyst(new ItemStack(ModBlocks.centerPedestal.get().asItem()), AltarRecipeCategory.TYPE);
        // Virtual recipes showing all outputs generated by the pot
        registry.addRecipeCatalyst(new ItemStack(ModBlocks.hat.get().asItem()), EnchantedRootRecipeCategory.TYPE);
    }

    @Override
    public void registerRecipes(IRecipeRegistration registration) {
        ClientLevel world = Minecraft.getInstance().level;
        if (world != null) {
            List<PedestalRecipe> pedestalRecipes = ModRecipeTypes.getRecipes(world, ModRecipeTypes.PEDESTAL_TYPE.get()).values().stream().map(RecipeHolder::value).toList();
            registration.addRecipes(AltarRecipeCategory.TYPE, pedestalRecipes);
            // Any enchanted colored root items not generated by the pedestal ritual will not have its output listed in JEI, as this will not find it.
            // So, modpack makers should not do that, then.
            List<EnchantedRootRecipe> enchantedRootRecipes = findEnchantedRootRecipes(pedestalRecipes);
            if (!enchantedRootRecipes.isEmpty()) {
                registration.addRecipes(EnchantedRootRecipeCategory.TYPE, enchantedRootRecipes);
            }
        }
    }

    /**
     * Inspect the pedestal recipes. For that have as output an enchanted colored root, register a virtual recipe
     * that will allow the player to see the output generated by the enchanted root linked to the pot of gold.
     */
    private List<EnchantedRootRecipe> findEnchantedRootRecipes(List<PedestalRecipe> recipes) {
        List<EnchantedRootRecipe> result = new ArrayList<>(recipes.size());

        for (PedestalRecipe recipe: recipes) {
            ItemStack stack = recipe.getResultItem(Minecraft.getInstance().level.registryAccess());
            if (stack.getItem() instanceof ColoredRoot) {
                ItemStack generated = ColoredRoot.getResourceItem(stack);
                if (!generated.isEmpty()) {
                    result.add(new EnchantedRootRecipe(stack));
                }
            }
        }
        return result;
    }

    @Override
    public void registerItemSubtypes(ISubtypeRegistration registration) {
        // Register items that are different because of NBT data, but share the same Item instance
        // Looks like you just give it some random unique string to differentiate them

        // Colored roots produced by the altar are differentiated on the resource they are associated with. Can be empty, but that should also serialize.
        for (RainbowColor tier: RainbowColor.values()) {
            ColoredRoot root = ModItems.getColoredRoot(tier).get();
            registration.registerSubtypeInterpreter(root, (stack, ctx) -> ColoredRoot.getResourceItem(stack).toString());
        }
    }
}
