package lonestarrr.arconia.client.integration.jei;

import java.util.ArrayList;
import java.util.List;
import lonestarrr.arconia.common.Arconia;
import lonestarrr.arconia.common.block.ModBlocks;
import lonestarrr.arconia.common.core.RainbowColor;
import lonestarrr.arconia.common.crafting.PedestalRecipe;
import lonestarrr.arconia.common.item.ColoredBranch;
import lonestarrr.arconia.common.item.ModItems;
import mezz.jei.api.IModPlugin;
import mezz.jei.api.JeiPlugin;
import mezz.jei.api.registration.IRecipeCatalystRegistration;
import mezz.jei.api.registration.IRecipeCategoryRegistration;
import mezz.jei.api.registration.IRecipeRegistration;
import mezz.jei.api.registration.ISubtypeRegistration;
import net.minecraft.client.Minecraft;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.RegistryAccess;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.ItemStack;

@JeiPlugin
public class JEIArconiaPlugin implements IModPlugin {
  private static final Identifier ID = Identifier.fromNamespaceAndPath(Arconia.MOD_ID, "main");

  @Override
  public Identifier getPluginUid() {
    return ID;
  }

  @Override
  public void registerCategories(IRecipeCategoryRegistration registry) {
    registry.addRecipeCategories(
        new AltarRecipeCategory(registry.getJeiHelpers().getGuiHelper()),
        new ImbuedBranchRecipeCategory(registry.getJeiHelpers().getGuiHelper()));
  }

  @Override
  public void registerRecipeCatalysts(IRecipeCatalystRegistration registry) {
    // The (main) blocks that process the recipes
    registry.addCraftingStation(AltarRecipeCategory.TYPE, ModBlocks.centerPedestal.get().asItem());
    // Virtual recipes showing all outputs generated by the pot
    registry.addCraftingStation(ImbuedBranchRecipeCategory.TYPE, ModBlocks.hat.get().asItem());
  }

  @Override
  public void registerRecipes(IRecipeRegistration registration) {
    // The vanilla 1.21.4 client only receives recipe display data, not raw recipes. Pedestal
    // recipes are shipped explicitly via NeoForge's OnDatapackSyncEvent#sendRecipes (see
    // PedestalRecipeSync) and stashed by ClientPedestalRecipes when the client receives them.
    List<PedestalRecipe> pedestalRecipes = ClientPedestalRecipes.getRecipes();
    if (pedestalRecipes.isEmpty()) {
      return;
    }
    registration.addRecipes(AltarRecipeCategory.TYPE, pedestalRecipes);
    List<ImbuedBranchRecipe> imbuedBranchRecipes =
        findImbuedBranchRecipes(pedestalRecipes, clientRegistryAccess());
    if (!imbuedBranchRecipes.isEmpty()) {
      registration.addRecipes(ImbuedBranchRecipeCategory.TYPE, imbuedBranchRecipes);
    }
  }

  private static HolderLookup.Provider clientRegistryAccess() {
    // PedestalRecipe#getResultItem ignores its HolderLookup argument, so any non-null provider
    // works.
    // Prefer the live level's registries while in-world; fall back to EMPTY for safety.
    var level = Minecraft.getInstance().level;
    return level != null ? level.registryAccess() : RegistryAccess.EMPTY;
  }

  /**
   * Inspects the pedestal recipes and creates a virtual JEI recipe for every one whose output is an
   * imbued colored branch — surfaces the resource each branch will yield in the pot of gold.
   */
  private List<ImbuedBranchRecipe> findImbuedBranchRecipes(
      List<PedestalRecipe> recipes, HolderLookup.Provider registries) {
    List<ImbuedBranchRecipe> result = new ArrayList<>(recipes.size());
    for (PedestalRecipe recipe : recipes) {
      ItemStack stack = recipe.getOutput();
      if (stack.getItem() instanceof ColoredBranch) {
        ItemStack generated = ColoredBranch.getResourceItem(stack);
        if (!generated.isEmpty()) {
          result.add(new ImbuedBranchRecipe(stack));
        }
      }
    }
    return result;
  }

  @Override
  public void registerItemSubtypes(ISubtypeRegistration registration) {
    // Register items that are different because of NBT data, but share the same Item instance
    // Looks like you just give it some random unique string to differentiate them

    // Colored branches produced by the altar are differentiated on the resource they are associated
    // with. Can be empty, but that should also serialize.
    for (RainbowColor tier : RainbowColor.values()) {
      ColoredBranch branch = ModItems.getColoredBranch(tier).get();
      registration.registerSubtypeInterpreter(
          branch, (stack, ctx) -> ColoredBranch.getResourceItem(stack).toString());
    }
  }
}
