package lonestarrr.arconia.client.effects;

import com.mojang.blaze3d.vertex.PoseStack;
import lonestarrr.arconia.common.block.ModBlocks;
import lonestarrr.arconia.common.block.entities.PotMultiBlockPrimaryBlockEntity;
import lonestarrr.arconia.common.core.RainbowColor;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.LevelRenderer;
import net.minecraft.client.renderer.SubmitNodeCollector;
import net.minecraft.client.renderer.blockentity.BlockEntityRenderer;
import net.minecraft.client.renderer.blockentity.BlockEntityRendererProvider;
import net.minecraft.client.renderer.blockentity.state.BlockEntityRenderState;
import net.minecraft.client.renderer.feature.ModelFeatureRenderer;
import net.minecraft.client.renderer.state.level.CameraRenderState;
import net.minecraft.core.BlockPos;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Set;

public class PotRenderer implements BlockEntityRenderer<PotMultiBlockPrimaryBlockEntity, PotRenderer.PotRenderState> {
    public static final long MIN_PARTICLE_INTERVAL = 25;
    public PotRenderer(BlockEntityRendererProvider.Context ctx) {}

    @Override
    public PotRenderState createRenderState() {
        return new PotRenderState();
    }

    @Override
    public void extractRenderState(
            @NotNull PotMultiBlockPrimaryBlockEntity blockEntity, PotRenderState renderState, float partialTick, Vec3 cameraPosition,
            @Nullable ModelFeatureRenderer.CrumblingOverlay breakProgress) {
        BlockEntityRenderer.super.extractRenderState(blockEntity, renderState, partialTick, cameraPosition, breakProgress);
        renderState.resourceItems = new ArrayList<>(blockEntity.getGeneratedResources());
        renderState.bonusColors = blockEntity.getBonusTreeColors();
        renderState.hasStorage = blockEntity.getStorageBlockPos() != null;
        renderState.detectedTier = blockEntity.getDetectedTier();
        renderState.storageFull = blockEntity.isStorageFull();
        renderState.itemGenerationCredits = blockEntity.getItemGenerationCredits();

        Level level = blockEntity.getLevel();
        if (level != null) {
            BlockPos potPos = renderState.blockPos;
            renderState.itemsLight = LevelRenderer.getLightCoords(level, potPos.above(2));
            renderState.leavesLight = LevelRenderer.getLightCoords(level, potPos.above(1));
        }
    }

    @Override
    public void submit(PotRenderState state, PoseStack poseStack, SubmitNodeCollector nodeCollector, CameraRenderState cameraRenderState) {
        Level level = Minecraft.getInstance().level;
        if (level == null) {
            return;
        }

        /*
         * This renders items generated by the pot. The pot itself is rendered as regular blocks.
         */
        List<ItemStack> resourceItems = state.resourceItems;
        if (!resourceItems.isEmpty()) {
            poseStack.pushPose();
            // Render items centered above the pot. The entity is at the bottom of the 2-y-layer pot.
            poseStack.translate(0.5, 2.1, 0.5);
            final float distanceFromCenter = 1.1f;
            final float scale = 0.6f;
            final int itemsPerLevel = 32;
            final float levelOffset = 0.25f; // Additional render offset (x+y) for each extra y layer
            ItemProjector.projectItemCarousel(resourceItems, poseStack, nodeCollector, state.itemsLight, 400, distanceFromCenter, scale, itemsPerLevel, levelOffset);
            poseStack.popPose();
        }

        /*
         * Render bonus tree leaves circling around the pot, one block above it.
         */
        Set<RainbowColor> bonusColors = state.bonusColors;
        if (bonusColors != null && !bonusColors.isEmpty()) {
            List<ItemStack> bonusLeaves = bonusColors.stream()
                    .sorted(Comparator.comparingInt(RainbowColor::getTier))
                    .map(color -> ModBlocks.getArconiumTreeLeaves(color).asItem().getDefaultInstance())
                    .toList();

            poseStack.pushPose();
            poseStack.translate(0.5, 1.3, 0.5);
            ItemProjector.projectItemCarousel(bonusLeaves, poseStack, nodeCollector, state.leavesLight, 1800, 1.3f, 0.4f, bonusLeaves.size(), 0f);
            poseStack.popPose();
        }

        // If for any reason items cannot be produced, visualize this by showing an icon above the pot
        BlockPos statePos = new BlockPos(0, 2, 0); // BER are always at 0, 0, 0
        int light = state.lightCoords;

        if (!state.hasStorage) {
            ItemProjector.projectItem(Items.CHEST.getDefaultInstance(), statePos, poseStack, nodeCollector, light, 0, true);
            ItemProjector.projectItem(Items.BARRIER.getDefaultInstance(), statePos, poseStack, nodeCollector, light, 0, true);
        } else if (state.detectedTier == null) {
            ItemProjector.projectItem(ModBlocks.getArconiumTreeLeaves(RainbowColor.RED).asItem().getDefaultInstance(), statePos, poseStack, nodeCollector, light, 0, true);
        } else if (state.storageFull) {
            ItemProjector.projectItem(Items.CHEST.getDefaultInstance(), statePos, poseStack, nodeCollector, light, 0, true);
        } else if (state.itemGenerationCredits <= 0) {
            ItemProjector.projectItem(ModBlocks.getArconiumTreeLeaves(state.detectedTier).asItem().getDefaultInstance(), statePos, poseStack, nodeCollector, light, 0, true);
        }
    }

    public static class PotRenderState extends BlockEntityRenderState {
        public List<ItemStack> resourceItems = List.of();
        public Set<RainbowColor> bonusColors = Set.of();
        public boolean hasStorage = false;
        public RainbowColor detectedTier = null;
        public boolean storageFull = false;
        public int itemGenerationCredits = 0;
        public int itemsLight = 15728880;
        public int leavesLight = 15728880;
    }
}
