package lonestarrr.arconia.client.effects;

import com.mojang.blaze3d.vertex.PoseStack;
import lonestarrr.arconia.common.block.ModBlocks;
import lonestarrr.arconia.common.block.entities.PotMultiBlockPrimaryBlockEntity;
import lonestarrr.arconia.common.core.RainbowColor;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.LevelRenderer;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.blockentity.BlockEntityRenderer;
import net.minecraft.client.renderer.blockentity.BlockEntityRendererProvider;
import net.minecraft.core.BlockPos;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.Level;
import org.jetbrains.annotations.NotNull;

import java.util.Comparator;
import java.util.List;
import java.util.Set;

public class PotRenderer implements BlockEntityRenderer<PotMultiBlockPrimaryBlockEntity> {
    public static final long MIN_PARTICLE_INTERVAL = 25;
    public PotRenderer(BlockEntityRendererProvider.Context ctx) {}


    @Override
    public void render(
            @NotNull PotMultiBlockPrimaryBlockEntity potEntity, float partialTicks, @NotNull PoseStack poseStack, @NotNull MultiBufferSource buffer, int combinedLight,
            int combinedOverlay) {
        Level level = Minecraft.getInstance().level;

        if (level == null) {
            return;
        }

        BlockPos potPos = potEntity.getBlockPos();

        /*
         * This renders items generated by the pot. The pot itself is rendered as regular blocks.
         */
        List<ItemStack> resourceItems = potEntity.getGeneratedResources();
        if (!resourceItems.isEmpty()) {
            BlockPos itemPos = potPos.above(2);
            final int light = LevelRenderer.getLightColor(level, itemPos);

            poseStack.pushPose();
            // Render items centered above the pot. The entity is at the bottom of the 2-y-layer pot.
            poseStack.translate(0.5, 2.1, 0.5);
            final float distanceFromCenter = 1.1f;
            final float scale = 0.6f;
            final int itemsPerLevel = 32;
            final float levelOffset = 0.25f; // Additional render offset (x+y) for each extra y layer
            ItemProjector.projectItemCarousel(resourceItems, poseStack, buffer, light, 400, distanceFromCenter, scale, itemsPerLevel, levelOffset);
            poseStack.popPose();
        }

        /*
         * Render bonus tree leaves circling around the pot, one block above it.
         */
        Set<RainbowColor> bonusColors = potEntity.getBonusTreeColors();
        if (!bonusColors.isEmpty()) {
            List<ItemStack> bonusLeaves = bonusColors.stream()
                    .sorted(Comparator.comparingInt(RainbowColor::getTier))
                    .map(color -> ModBlocks.getArconiumTreeLeaves(color).asItem().getDefaultInstance())
                    .toList();
            BlockPos leavesPos = potPos.above(1);
            final int leavesLight = LevelRenderer.getLightColor(level, leavesPos);

            poseStack.pushPose();
            poseStack.translate(0.5, 1.3, 0.5);
            ItemProjector.projectItemCarousel(bonusLeaves, poseStack, buffer, leavesLight, 1800, 1.3f, 0.4f, bonusLeaves.size(), 0f);
            poseStack.popPose();
        }

        // If for any reason items cannot be produced, visualize this by showing an icon above the pot
        BlockPos statePos = new BlockPos(0, 2, 0); // BER are always at 0, 0, 0

        if (potEntity.getStorageBlockPos() == null) {
            ItemProjector.projectItem(Items.CHEST.getDefaultInstance(), statePos, poseStack, buffer, combinedLight, combinedOverlay, true);
            ItemProjector.projectItem(Items.BARRIER.getDefaultInstance(), statePos, poseStack, buffer, combinedLight, combinedOverlay, true);
        } else if (potEntity.getDetectedTier() == null) {
            ItemProjector.projectItem(ModBlocks.getArconiumTreeLeaves(RainbowColor.RED).asItem().getDefaultInstance(), statePos, poseStack, buffer, combinedLight, combinedOverlay, true);
        } else if (potEntity.isStorageFull()) {
            ItemProjector.projectItem(Items.CHEST.getDefaultInstance(), statePos, poseStack, buffer, combinedLight, combinedOverlay, true);
        }
    }
}
