package lonestarrr.arconia.client.effects;

import com.mojang.blaze3d.vertex.PoseStack;
import lonestarrr.arconia.common.block.entities.PotMultiBlockPrimaryBlockEntity;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.LevelRenderer;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.blockentity.BlockEntityRenderer;
import net.minecraft.client.renderer.blockentity.BlockEntityRendererProvider;
import net.minecraft.core.BlockPos;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.Level;
import org.jetbrains.annotations.NotNull;

import java.util.List;

public class PotRenderer implements BlockEntityRenderer<PotMultiBlockPrimaryBlockEntity> {
    public static final long MIN_PARTICLE_INTERVAL = 25;
    public PotRenderer(BlockEntityRendererProvider.Context ctx) {}


    @Override
    public void render(
            PotMultiBlockPrimaryBlockEntity potEntity, float partialTicks, @NotNull PoseStack poseStack, @NotNull MultiBufferSource buffer, int combinedLight,
            int combinedOverlay) {
        Level level = Minecraft.getInstance().level;

        if (level == null) {
            return;
        }

        /*
         * The pot itself is rendered through regular means. This renders items that are generated by the pots above it
         */
        List<ItemStack> resourceItems = potEntity.getGeneratedResources();
        if (resourceItems.isEmpty()) {
            return;
        }
        BlockPos potPos = potEntity.getBlockPos();
        BlockPos itemPos = potPos.above(2);
        final int ticksPerRotation = 400;
        final int light = LevelRenderer.getLightColor(level, itemPos);

        poseStack.pushPose();
        // Render items centered above the pot. The entity is at the bottom of the 2-y-layer pot.
        poseStack.translate(0.5, 2.1, 0.5);
        final float distanceFromCenter = 1.1f;
        final float scale = 0.6f;
        final int itemsPerLevel = 32;
        final float levelOffset = 0.25f; // Additional render offset (x+y) for each extra y layer
        ItemProjector.projectItemCarousel(resourceItems, poseStack, buffer, light, ticksPerRotation, distanceFromCenter, scale, itemsPerLevel, levelOffset);
        poseStack.popPose();
    }
}
