package lonestarrr.arconia.data.recipes;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import com.mojang.serialization.Dynamic;
import com.mojang.serialization.JsonOps;
import lonestarrr.arconia.common.Arconia;
import lonestarrr.arconia.common.block.ModBlocks;
import lonestarrr.arconia.common.core.BlockNames;
import lonestarrr.arconia.common.core.ItemNames;
import lonestarrr.arconia.common.core.RainbowColor;
import lonestarrr.arconia.common.crafting.ModRecipeTypes;
import lonestarrr.arconia.common.item.ColoredRoot;
import lonestarrr.arconia.common.item.MagicInABottle;
import lonestarrr.arconia.common.item.ModItems;
import net.minecraft.core.Registry;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.recipes.FinishedRecipe;
import net.minecraft.data.recipes.RecipeProvider;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.NbtOps;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Blocks;

import javax.annotation.Nullable;
import java.util.Arrays;
import java.util.function.Consumer;

/**
 * Registers recipes specific for the pedestal crafting ritual
 */
public class PedestalProvider extends RecipeProvider {

    public PedestalProvider(DataGenerator gen) {
        super(gen);
    }

    @Override
    public String getName() {
        return "Arconia pedestal recipes";
    }

    @Override
    protected void buildCraftingRecipes(Consumer<FinishedRecipe> consumer) {
        registerColoredRootRecipes(consumer);
        registerGoldArconiumBlocks(consumer);
        registerInfiniteGoldArconiumBlocks(consumer);
        registerMisc(consumer);
    }

    /*
     * Recipes for colored roots with nbt data on them indicating what item will be generated by the mod's resource generator
     */
    private void registerColoredRootRecipes(Consumer<FinishedRecipe> consumer) {
        final Ingredient clover = Ingredient.of(ModItems.fourLeafClover);

        int durationTicks = 200; // Time for ritual to create the item from the recipe
        int interval = 10; // Resource Generation - minimum interval, in resource generator events, between resource generation
        int count = 1; // Number of items to generate per resource generation event
        int cost = 1; // Number of coins the resource generated should cost
        RainbowColor tier = RainbowColor.RED;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, clover, clover, clover));
        for (Item item: new Item[] { Items.OAK_LOG, Items.BIRCH_LOG, Items.SAND, Items.GRAVEL, Items.DIRT }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }

        tier = RainbowColor.ORANGE;
        durationTicks = 200;
        interval = 9;
        cost = 2;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(RainbowColor.RED)), clover, clover));
        for (Item item: new Item[] { Items.SPRUCE_LOG, Items.ACACIA_LOG, Items.ANDESITE}) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }

        consumer.accept(makeEnchantedColoredRoot(tier, Items.LEATHER, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.LEATHER_CHESTPLATE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.BEEF, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.ROTTEN_FLESH)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.COBBLESTONE, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.SMOOTH_STONE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.BAMBOO, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.SCAFFOLDING)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.POTATO, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.POISONOUS_POTATO)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.CARROT, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.CARROT_ON_A_STICK)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.ROTTEN_FLESH, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.COOKED_BEEF)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.CLAY_BALL, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.TERRACOTTA)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.PORKCHOP, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.COOKED_PORKCHOP)));

        tier = RainbowColor.YELLOW;
        durationTicks = 400;
        interval = 8;
        cost = 4;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(RainbowColor.ORANGE)), clover, clover));
        for (Item item: new Item[] { Items.DARK_OAK_LOG, Items.JUNGLE_LOG, Items.GRANITE  }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }

        consumer.accept(makeEnchantedColoredRoot(tier, Items.IRON_NUGGET, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.IRON_BARS)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.SUGAR_CANE, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.CAKE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.WHEAT, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.HAY_BLOCK)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.WHEAT_SEEDS, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.WHEAT)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.STRING, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.FISHING_ROD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.COAL, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.CHARCOAL)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.BONE, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.BONE_BLOCK)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.BROWN_MUSHROOM, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.RED_MUSHROOM)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.RED_MUSHROOM, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.BROWN_MUSHROOM)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.BEETROOT, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.BEETROOT_SOUP)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.STONE, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.FURNACE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.EGG, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.COOKED_CHICKEN)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.FEATHER, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.CHICKEN)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.RABBIT, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.CARROT)));

        tier = RainbowColor.GREEN;
        durationTicks = 400;
        interval = 7;
        cost = 8;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(RainbowColor.YELLOW)), clover, clover));
        for (Item item: new Item[] { Items.GOLD_NUGGET, Items.DIORITE, Items.SLIME_BALL, Items.COBBLED_DEEPSLATE }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }

        consumer.accept(makeEnchantedColoredRoot(tier, Items.LAPIS_LAZULI, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.LAPIS_BLOCK)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.GUNPOWDER, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.TNT_MINECART)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.SPIDER_EYE, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.FERMENTED_SPIDER_EYE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.SMOOTH_STONE, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.BLAST_FURNACE)));

        tier = RainbowColor.LIGHT_BLUE;
        durationTicks = 400;
        interval = 6;
        cost = 16;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(RainbowColor.GREEN)), clover, clover));
        for (Item item: new Item[] {Items.SOUL_SAND,Items.NETHERRACK, Items.CRIMSON_STEM, Items.WARPED_STEM, Items.BLACKSTONE, Items.BASALT }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }

        consumer.accept(makeEnchantedColoredRoot(tier, Items.REDSTONE, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.REDSTONE_BLOCK)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.ENDER_PEARL, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.ENDER_CHEST)));

        tier = RainbowColor.BLUE;
        durationTicks = 400;
        interval = 5;
        cost = 32;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(RainbowColor.LIGHT_BLUE)), clover, clover));
        for (Item item: new Item[] { Items.SOUL_SOIL, Items.OBSIDIAN }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }

        // By here, going to assume even in skyblock that players have access to structures in the nether
        consumer.accept(makeEnchantedColoredRoot(tier, Items.NETHER_WART, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.NETHER_WART), Ingredient.of(Items.NETHER_BRICK)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.BLAZE_ROD, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.BLAZE_ROD), Ingredient.of(Items.BLAZE_ROD), Ingredient.of(Items.BLAZE_ROD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.DIAMOND, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.IRON_BLOCK), Ingredient.of(Items.GOLD_BLOCK)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.GLOWSTONE_DUST, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.IRON_BLOCK), Ingredient.of(Items.GLOWSTONE)));

        tier = RainbowColor.PURPLE;
        durationTicks = 800;
        interval = 4;
        cost = 64;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(RainbowColor.BLUE)), clover, clover));
//        for (Item item: new Item[] { Items.EMERALD }) {
//            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
//        }
        consumer.accept(makeEnchantedColoredRoot(tier, Items.EMERALD, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.DIAMOND), Ingredient.of(Items.GREEN_DYE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.WITHER_SKELETON_SKULL, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.WITHER_SKELETON_SKULL), Ingredient.of(Items.WITHER_SKELETON_SKULL), Ingredient.of(Items.WITHER_SKELETON_SKULL)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.GHAST_TEAR, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.CRYING_OBSIDIAN)));

        tier = RainbowColor.MAGENTA;
        durationTicks = 800;
        interval = 3;
        cost = 128;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(RainbowColor.PURPLE)), clover, clover));
        for (Item item: new Item[] { Items.END_STONE }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }
        consumer.accept(makeEnchantedColoredRoot(tier, Items.ANCIENT_DEBRIS, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.NETHER_STAR)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.CHORUS_FRUIT, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.PURPUR_BLOCK), Ingredient.of(Items.APPLE)));

        tier = RainbowColor.PINK;
        durationTicks = 800;
        interval = 2;
        cost = 256;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(RainbowColor.MAGENTA)), clover, clover));
        for (Item item: new Item[] { Items.SHULKER_SHELL }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }
        consumer.accept(makeEnchantedColoredRoot(tier, Items.DRAGON_BREATH, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.DRAGON_HEAD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.DRAGON_EGG, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.DRAGON_HEAD), Ingredient.of(Items.EGG)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.NETHER_STAR, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(Items.END_CRYSTAL)));
    }

    private void registerGoldArconiumBlocks(Consumer<FinishedRecipe> consumer) {
        RainbowColor.stream().forEach(color -> consumer.accept(makeGoldArconiumBlock(color)));
    }

    private void registerInfiniteGoldArconiumBlocks(Consumer<FinishedRecipe> consumer) {
        RainbowColor.stream().forEach(color -> consumer.accept(makeInfiniteGoldArconiumBlock(color)));
    }

    private void registerMisc(Consumer<FinishedRecipe> consumer) {
        // Register Magic-In-A-Bottle (TM) for each tier
        RainbowColor.stream().forEach(color -> {
           ItemStack output = MagicInABottle.getBottleForTier(color);
           Ingredient bottle = Ingredient.of(color == RainbowColor.RED ? Items.GLASS_BOTTLE : ModItems.magicInABottle); //any tier bottle will work
           Ingredient essence = Ingredient.of(ModItems.getArconiumEssence(color));
           ResourceLocation recipeId = id(color.getTierName() + "_" + ItemNames.MAGIC_IN_A_BOTTLE);
           final int durationTicks = 100 + (color.getTier() * 100);
           consumer.accept(new PedestalFinishedRecipe(recipeId, output, durationTicks, bottle, essence));
        });
    }

    private static FinishedRecipe makeGoldArconiumBlock(RainbowColor color) {
        ItemStack output = new ItemStack(ModBlocks.getGoldArconiumBlock(color).asItem());
        Ingredient goldBlock = Ingredient.of(Blocks.GOLD_BLOCK.asItem());
        Ingredient essence = Ingredient.of(ModItems.getArconiumEssence(color));
        ResourceLocation recipeId = id(color.getTierName() + BlockNames.GOLD_ARCONIUM_BLOCK_SUFFIX);
        final int durationTicks = 100 + (color.getTier() * 100);
        return new PedestalFinishedRecipe(recipeId, output, durationTicks, goldBlock, essence, essence, essence, essence, essence, essence);
    }

    private static FinishedRecipe makeInfiniteGoldArconiumBlock(RainbowColor color) {
        ItemStack output = new ItemStack(ModBlocks.getInfiniteGoldArconiumBlock(color).asItem());
        Ingredient goldArconiumBlock = Ingredient.of(ModBlocks.getGoldArconiumBlock(color).asItem());
        Ingredient arconiumBlock = Ingredient.of(ModBlocks.getArconiumBlock(color).asItem());
        ResourceLocation recipeId = id(color.getTierName() + BlockNames.INFINITE_GOLD_ARCONIUM_BLOCK_SUFFIX);
        final int durationTicks = 100 + (color.getTier() * 100);
        return new PedestalFinishedRecipe(recipeId, output, durationTicks, goldArconiumBlock, arconiumBlock, arconiumBlock, arconiumBlock, arconiumBlock, arconiumBlock, arconiumBlock, arconiumBlock);
    }


    /**
     * Craft an enchanted colored root for a given item to be generated as part of the resource generation of the mod
     *
     * @param tier Tier of colored root to make
     * @param resourceItem The item to be produced by the tree
     * @param durationTicks time the crafting recipe will take to make the root
     * @param resourceGenCount Number of items to generate per resource generation event
     * @param resourceGenInterval Frequency with which resource is generated. An interval of 1 is fastest. Interval length is determined by the pot of gold and is typically no less than 5 ticks.
     * @param resourceCoinCost How many coins it costs to generate this resource
     * @param ingredients
     * @return
     */
    private static FinishedRecipe makeEnchantedColoredRoot(RainbowColor tier, ItemLike resourceItem, int durationTicks, int resourceGenInterval, int resourceGenCount, int resourceCoinCost, Ingredient... ingredients) {
        Item root = ModItems.getColoredRoot(tier);
        ItemStack coloredRoot = new ItemStack(root);
        ColoredRoot.setResourceItem(coloredRoot, resourceItem, resourceGenInterval, resourceGenCount, resourceCoinCost);
        ResourceLocation rootId = Registry.ITEM.getKey(root);
        ResourceLocation itemId = Registry.ITEM.getKey(resourceItem.asItem());
        ResourceLocation recipeId = id(rootId.getPath() + "/" + itemId.getNamespace() + "_" + itemId.getPath());
        Arconia.logger.info("***** Recipe ID: " + recipeId);
        Ingredient[] newIngredients = Arrays.copyOf(ingredients, ingredients.length + 1);
        newIngredients[ingredients.length] = Ingredient.of(root);
        return new PedestalFinishedRecipe(recipeId, coloredRoot, durationTicks, newIngredients);
    }

    private static ResourceLocation id(String s) {
        return new ResourceLocation(Arconia.MOD_ID, "pedestal/" + s);
    }


    private static class PedestalFinishedRecipe implements FinishedRecipe {
        private final ResourceLocation id;
        private final ItemStack output;
        private final Ingredient[] inputs;
        private final int durationTicks;

        private PedestalFinishedRecipe(ResourceLocation id, ItemStack output, int durationTicks, Ingredient... inputs) {
            this.id = id;
            this.output = output;
            this.durationTicks = durationTicks;
            this.inputs = inputs;
        }

        @Override
        public void serializeRecipeData(JsonObject json) {
            json.add("output", serializeStack(output));
            json.add("durationTicks", new JsonPrimitive(durationTicks));
            JsonArray ingredients = new JsonArray();
            for (Ingredient ingredient : inputs) {
                ingredients.add(ingredient.toJson());
            }
            json.add("ingredients", ingredients);
        }

        private static JsonObject serializeStack(ItemStack stack) {
            CompoundTag nbt = stack.save(new CompoundTag());
            byte c = nbt.getByte("Count");
            if (c != 1) {
                nbt.putByte("count", c);
            }
            nbt.remove("Count");
            renameTag(nbt, "id", "item");
            renameTag(nbt, "tag", "nbt");
            Dynamic<Tag> dyn = new Dynamic<>(NbtOps.INSTANCE, nbt);
            return dyn.convert(JsonOps.INSTANCE).getValue().getAsJsonObject();
        }

        private static void renameTag(CompoundTag nbt, String oldName, String newName) {
            Tag tag = nbt.get(oldName);
            if (tag != null) {
                nbt.remove(oldName);
                nbt.put(newName, tag);
            }
        }

        @Override
        public ResourceLocation getId() {
            return id;
        }

        @Override
        public RecipeSerializer<?> getType() {
            return ModRecipeTypes.PEDESTAL_SERIALIZER;
        }

        @Nullable
        @Override
        public JsonObject serializeAdvancement() {
            return null;
        }

        @Nullable
        @Override
        public ResourceLocation getAdvancementId() {
            return null;
        }
    }
}