package lonestarrr.arconia.data.recipes;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import com.mojang.serialization.Dynamic;
import com.mojang.serialization.JsonOps;
import lonestarrr.arconia.common.Arconia;
import lonestarrr.arconia.common.block.ModBlocks;
import lonestarrr.arconia.common.core.BlockNames;
import lonestarrr.arconia.common.core.ItemNames;
import lonestarrr.arconia.common.core.RainbowColor;
import lonestarrr.arconia.common.crafting.ModRecipeTypes;
import lonestarrr.arconia.common.item.ColoredRoot;
import lonestarrr.arconia.common.item.ModItems;
import net.minecraft.core.Registry;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.recipes.FinishedRecipe;
import net.minecraft.data.recipes.RecipeProvider;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.NbtOps;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Blocks;
import org.jetbrains.annotations.NotNull;

import javax.annotation.Nullable;
import java.util.Arrays;
import java.util.function.Consumer;

/**
 * Registers recipes specific for the pedestal crafting ritual
 */
public class PedestalProvider extends RecipeProvider {

    public PedestalProvider(DataGenerator gen) {
        super(gen);
    }

    @Override
    public String getName() {
        return "Arconia pedestal recipes";
    }

    @Override
    protected void buildCraftingRecipes(Consumer<FinishedRecipe> consumer) {
        registerColoredRootRecipes(consumer);
        registerArconiumIngotRecipes(consumer);
        registerInfiniteGoldArconiumBlocks(consumer);
        registerMisc(consumer);
    }

    /*
     * Recipes for colored roots with nbt data on them indicating what item will be generated by the mod's resource generator
     */
    private void registerColoredRootRecipes(Consumer<FinishedRecipe> consumer) {
        final Ingredient clover = Ingredient.of(ModItems.fourLeafClover.get());

        int durationTicks = 60; // Time for ritual to create the item from the recipe
        int count = 1; // Number of items to generate per resource generation event
        RainbowColor tier = RainbowColor.RED;

        consumer.accept(
                makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier).get(), durationTicks, count, clover, clover,
                        Ingredient.of(ModBlocks.getArconiumTreeSapling(tier).get().asItem()), Ingredient.of(
                                RainbowColor.woolByTier(tier))));
        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumIngot(tier).get(), durationTicks, count, clover, clover,
                Ingredient.of(ModBlocks.getArconiumBlock(tier).get().asItem())));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.RED_DYE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.BEETROOT), Ingredient.of(Items.RED_WOOL), Ingredient.of(Items.RED_CONCRETE), Ingredient.of(Items.RED_TERRACOTTA)));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.KELP, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.KELP), Ingredient.of(Items.DRIED_KELP_BLOCK), Ingredient.of(Items.DRIED_KELP_BLOCK)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.APPLE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.APPLE), Ingredient.of(Items.OAK_SAPLING), Ingredient.of(Items.STONE_HOE)));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.SAND, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.SAND), Ingredient.of(Items.SANDSTONE), Ingredient.of(Items.SANDSTONE), Ingredient.of(Items.STONE_SHOVEL)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.GRAVEL, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.GRAVEL), Ingredient.of(Items.FLINT), Ingredient.of(Items.FLINT), Ingredient.of(Items.STONE_SHOVEL)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.DIRT, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.DIRT), Ingredient.of(Items.COARSE_DIRT), Ingredient.of(Items.MUD), Ingredient.of(Items.STONE_SHOVEL)));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.OAK_LOG, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.OAK_LOG), Ingredient.of(Items.OAK_LOG), Ingredient.of(Items.OAK_LOG), Ingredient.of(Items.OAK_SAPLING), Ingredient.of(Items.STONE_AXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.DARK_OAK_LOG, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.DARK_OAK_LOG), Ingredient.of(Items.DARK_OAK_LOG), Ingredient.of(Items.DARK_OAK_LOG), Ingredient.of(Items.DARK_OAK_SAPLING), Ingredient.of(Items.STONE_AXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.BIRCH_LOG, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.BIRCH_LOG), Ingredient.of(Items.BIRCH_LOG), Ingredient.of(Items.BIRCH_LOG), Ingredient.of(Items.BIRCH_SAPLING), Ingredient.of(Items.STONE_AXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.JUNGLE_LOG, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.JUNGLE_LOG), Ingredient.of(Items.JUNGLE_LOG), Ingredient.of(Items.JUNGLE_LOG), Ingredient.of(Items.JUNGLE_SAPLING), Ingredient.of(Items.STONE_AXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.SPRUCE_LOG, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.SPRUCE_LOG), Ingredient.of(Items.SPRUCE_LOG), Ingredient.of(Items.SPRUCE_LOG), Ingredient.of(Items.SPRUCE_SAPLING), Ingredient.of(Items.STONE_AXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.ACACIA_LOG, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.ACACIA_LOG), Ingredient.of(Items.ACACIA_LOG), Ingredient.of(Items.ACACIA_LOG), Ingredient.of(Items.ACACIA_SAPLING), Ingredient.of(Items.STONE_AXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.MANGROVE_LOG, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.MANGROVE_LOG), Ingredient.of(Items.MANGROVE_LOG), Ingredient.of(Items.MANGROVE_LOG), Ingredient.of(Items.MANGROVE_PROPAGULE), Ingredient.of(Items.STONE_AXE)));
        
        RainbowColor previousTier = tier;
        tier = RainbowColor.ORANGE;

        consumer.accept(
                makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier).get(), durationTicks, count, clover, clover,
                        Ingredient.of(ModBlocks.getArconiumTreeSapling(tier).get().asItem()), Ingredient.of(
                                RainbowColor.woolByTier(tier))));
        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumIngot(tier).get(), durationTicks, count, clover, clover,
                Ingredient.of(ModBlocks.getArconiumBlock(tier).get().asItem())));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.ORANGE_DYE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.RED_DYE), Ingredient.of(Items.YELLOW_DYE), Ingredient.of(Items.ORANGE_WOOL), Ingredient.of(Items.ORANGE_CONCRETE), Ingredient.of(Items.ORANGE_TERRACOTTA)));

        for (Item item : new Item[]{Items.SUGAR_CANE, Items.WHEAT, Items.PUMPKIN, Items.MELON}) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                    Ingredient.of(item), Ingredient.of(item), Ingredient.of(item), Ingredient.of(Items.STONE_HOE)));
        }
        for (Item item : new Item[]{Items.BEEF, Items.CHICKEN, Items.MUTTON, Items.COD, Items.SALMON}) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                    Ingredient.of(item), Ingredient.of(item), Ingredient.of(item), Ingredient.of(Items.STONE_SWORD)));
        }
        
        for (Item item : new Item[]{Items.COBBLESTONE, Items.STONE, Items.DEEPSLATE, Items.DIORITE, Items.GRANITE, Items.CALCITE, Items.ANDESITE}) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                    Ingredient.of(item), Ingredient.of(item), Ingredient.of(item), Ingredient.of(Items.STONE_PICKAXE)));
        }
        consumer.accept(makeEnchantedColoredRoot(tier, Items.RAW_COPPER, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.RAW_COPPER_BLOCK), Ingredient.of(Items.RAW_COPPER_BLOCK), Ingredient.of(Items.RAW_COPPER_BLOCK), Ingredient.of(Items.IRON_PICKAXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.COAL, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.COAL_BLOCK), Ingredient.of(Items.COAL_BLOCK), Ingredient.of(Items.COAL_BLOCK), Ingredient.of(Items.IRON_PICKAXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.STRING, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.STRING), Ingredient.of(Items.WHITE_WOOL), Ingredient.of(Items.LOOM)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.MUD, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.MUD), Ingredient.of(Items.DIRT), Ingredient.of(Items.GLASS_BOTTLE), Ingredient.of(Items.WATER_BUCKET)));

        previousTier = tier;
        tier = RainbowColor.YELLOW;

        consumer.accept(
                makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier).get(), durationTicks, count, clover, clover,
                        Ingredient.of(ModBlocks.getArconiumTreeSapling(tier).get().asItem()), Ingredient.of(
                                RainbowColor.woolByTier(tier))));
        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumIngot(tier).get(), durationTicks, count, clover, clover,
                Ingredient.of(ModBlocks.getArconiumBlock(tier).get().asItem())));
        for (Item item : new Item[]{Items.CACTUS}) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                    Ingredient.of(item), Ingredient.of(item), Ingredient.of(item)));
        }

        consumer.accept(makeEnchantedColoredRoot(tier, Items.YELLOW_DYE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.DANDELION), Ingredient.of(Items.YELLOW_WOOL), Ingredient.of(Items.YELLOW_CONCRETE), Ingredient.of(Items.YELLOW_TERRACOTTA)));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.SPIDER_EYE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.SPIDER_EYE), Ingredient.of(Items.STRING), Ingredient.of(Items.STRING), Ingredient.of(Items.IRON_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.FEATHER, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.CHICKEN), Ingredient.of(Items.EGG), Ingredient.of(Items.FEATHER), Ingredient.of(Items.IRON_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.RAW_IRON, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.RAW_IRON_BLOCK), Ingredient.of(Items.RAW_IRON_BLOCK), Ingredient.of(Items.RAW_IRON_BLOCK), Ingredient.of(Items.IRON_PICKAXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.LEATHER, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.LEATHER_HELMET), Ingredient.of(Items.LEATHER_CHESTPLATE), Ingredient.of(Items.LEATHER_LEGGINGS), Ingredient.of(Items.LEATHER_BOOTS), Ingredient.of(Items.ITEM_FRAME)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.BONE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.BONE_BLOCK), Ingredient.of(Items.BONE_BLOCK), Ingredient.of(Items.BONE_BLOCK), Ingredient.of(Items.IRON_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.PORKCHOP, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.PORKCHOP), Ingredient.of(Items.PORKCHOP), Ingredient.of(Items.PORKCHOP), Ingredient.of(Items.IRON_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.ROTTEN_FLESH, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(Items.IRON_SHOVEL)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.POTATO, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.POTATO), Ingredient.of(Items.POTATO), Ingredient.of(Items.POTATO), Ingredient.of(Items.IRON_HOE), Ingredient.of(Items.WATER_BUCKET)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.BEETROOT, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.BEETROOT), Ingredient.of(Items.BEETROOT), Ingredient.of(Items.BEETROOT), Ingredient.of(Items.IRON_HOE), Ingredient.of(Items.WATER_BUCKET)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.CARROT, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.CARROT), Ingredient.of(Items.CARROT), Ingredient.of(Items.CARROT), Ingredient.of(Items.IRON_HOE), Ingredient.of(Items.WATER_BUCKET)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.ARROW, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.BONE), Ingredient.of(Items.ARROW), Ingredient.of(Items.SHIELD), Ingredient.of(Items.IRON_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.WHITE_WOOL, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.MUTTON), Ingredient.of(Items.WHITE_WOOL), Ingredient.of(Items.BLACK_WOOL), Ingredient.of(Items.SHEARS)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.HONEYCOMB, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.HONEYCOMB_BLOCK), Ingredient.of(Items.HONEYCOMB_BLOCK), Ingredient.of(Items.HONEYCOMB_BLOCK), Ingredient.of(Items.CAMPFIRE), Ingredient.of(Items.SHEARS)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.HONEY_BOTTLE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.HONEY_BLOCK), Ingredient.of(Items.HONEY_BLOCK), Ingredient.of(Items.HONEY_BLOCK), Ingredient.of(Items.CAMPFIRE), Ingredient.of(Items.GLASS_BOTTLE)));

        // Building blocks
        consumer.accept(makeEnchantedColoredRoot(tier, Items.NETHER_BRICK, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.NETHERRACK), Ingredient.of(Items.NETHER_BRICK), Ingredient.of(Items.NETHER_BRICK), Ingredient.of(Items.IRON_PICKAXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.SOUL_SAND, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.SOUL_SAND), Ingredient.of(Items.SOUL_CAMPFIRE), Ingredient.of(Items.BONE_BLOCK), Ingredient.of(Items.IRON_SHOVEL)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.SOUL_SOIL, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.SOUL_SOIL), Ingredient.of(Items.SOUL_CAMPFIRE), Ingredient.of(Items.BONE_BLOCK), Ingredient.of(Items.IRON_SHOVEL)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.BLACKSTONE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.BLACKSTONE), Ingredient.of(Items.BLACKSTONE_STAIRS), Ingredient.of(Items.BLACKSTONE_WALL), Ingredient.of(Items.IRON_PICKAXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.BASALT, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.BASALT), Ingredient.of(Items.POLISHED_BASALT), Ingredient.of(Items.SMOOTH_BASALT), Ingredient.of(Items.IRON_PICKAXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.CRIMSON_STEM, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.CRIMSON_STEM), Ingredient.of(Items.NETHER_WART_BLOCK), Ingredient.of(Items.CRIMSON_FUNGUS), Ingredient.of(Items.IRON_AXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.WARPED_STEM, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.WARPED_STEM), Ingredient.of(Items.WARPED_WART_BLOCK), Ingredient.of(Items.WARPED_FUNGUS), Ingredient.of(Items.IRON_AXE)));

        previousTier = tier;
        tier = RainbowColor.GREEN;

        consumer.accept(
                makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier).get(), durationTicks, count, clover, clover,
                        Ingredient.of(ModBlocks.getArconiumTreeSapling(tier).get().asItem()), Ingredient.of(
                                RainbowColor.woolByTier(tier))));
        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumIngot(tier).get(), durationTicks, count, clover, clover,
                Ingredient.of(ModBlocks.getArconiumBlock(tier).get().asItem())));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.GREEN_DYE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.CACTUS), Ingredient.of(Items.GREEN_WOOL), Ingredient.of(Items.GREEN_CONCRETE), Ingredient.of(Items.GREEN_TERRACOTTA)));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.AMETHYST_SHARD, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.AMETHYST_BLOCK), Ingredient.of(Items.AMETHYST_BLOCK), Ingredient.of(Items.AMETHYST_BLOCK), Ingredient.of(Items.IRON_PICKAXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.RAW_GOLD, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.RAW_GOLD_BLOCK), Ingredient.of(Items.RAW_GOLD_BLOCK), Ingredient.of(Items.RAW_GOLD_BLOCK), Ingredient.of(Items.IRON_PICKAXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.LAPIS_LAZULI, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.LAPIS_BLOCK), Ingredient.of(Items.LAPIS_BLOCK), Ingredient.of(Items.LAPIS_BLOCK), Ingredient.of(Items.IRON_PICKAXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.REDSTONE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.REDSTONE_BLOCK), Ingredient.of(Items.REDSTONE_BLOCK), Ingredient.of(Items.REDSTONE_BLOCK), Ingredient.of(Items.IRON_PICKAXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.GUNPOWDER, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.TNT), Ingredient.of(Items.TNT), Ingredient.of(Items.TNT), Ingredient.of(Items.FLINT_AND_STEEL), Ingredient.of(Items.IRON_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.INK_SAC, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.INK_SAC), Ingredient.of(Items.INK_SAC), Ingredient.of(Items.INK_SAC), Ingredient.of(Items.IRON_SWORD)));

        previousTier = tier;
        tier = RainbowColor.LIGHT_BLUE;

        consumer.accept(
                makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier).get(), durationTicks, count, clover, clover,
                        Ingredient.of(ModBlocks.getArconiumTreeSapling(tier).get().asItem()), Ingredient.of(
                                RainbowColor.woolByTier(tier))));
        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumIngot(tier).get(), durationTicks, count, clover, clover,
                Ingredient.of(ModBlocks.getArconiumBlock(tier).get().asItem())));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.LIGHT_BLUE_DYE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.BLUE_ORCHID), Ingredient.of(Items.LIGHT_BLUE_WOOL), Ingredient.of(Items.LIGHT_BLUE_CONCRETE), Ingredient.of(Items.LIGHT_BLUE_TERRACOTTA)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.PRISMARINE_SHARD, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.PRISMARINE_SHARD), Ingredient.of(Items.SEA_LANTERN), Ingredient.of(Items.DARK_PRISMARINE), Ingredient.of(Items.DIAMOND_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.PRISMARINE_CRYSTALS, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.PRISMARINE_CRYSTALS), Ingredient.of(Items.SEA_LANTERN), Ingredient.of(Items.SPONGE), Ingredient.of(Items.DIAMOND_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.OBSIDIAN, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.OBSIDIAN), Ingredient.of(Items.LAVA_BUCKET), Ingredient.of(Items.CRYING_OBSIDIAN), Ingredient.of(Items.DIAMOND_PICKAXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.SLIME_BALL, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.SLIME_BLOCK), Ingredient.of(Items.SLIME_BLOCK), Ingredient.of(Items.SLIME_BLOCK), Ingredient.of(Items.DIAMOND_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.EMERALD, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.EMERALD_BLOCK), Ingredient.of(Items.EMERALD_BLOCK), Ingredient.of(Items.EMERALD_BLOCK), Ingredient.of(Items.FLETCHING_TABLE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.END_STONE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.END_STONE), Ingredient.of(Items.END_STONE_BRICKS), Ingredient.of(Items.END_STONE_BRICK_WALL), Ingredient.of(Items.DIAMOND_PICKAXE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.CHORUS_FRUIT, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.CHORUS_FRUIT), Ingredient.of(Items.CHORUS_FLOWER), Ingredient.of(Items.END_STONE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.ENDER_PEARL, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.ENDER_PEARL), Ingredient.of(Items.ENDER_PEARL), Ingredient.of(Items.ENDER_PEARL), Ingredient.of(Items.DIAMOND_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.EXPERIENCE_BOTTLE, durationTicks, 4, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.ENCHANTING_TABLE), Ingredient.of(Items.BOOKSHELF), Ingredient.of(Items.ANVIL), Ingredient.of(Items.GRINDSTONE), Ingredient.of(Items.LAPIS_BLOCK)));


        previousTier = tier;
        tier = RainbowColor.BLUE;

        consumer.accept(
                makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier).get(), durationTicks, count, clover, clover,
                        Ingredient.of(ModBlocks.getArconiumTreeSapling(tier).get().asItem()), Ingredient.of(
                                RainbowColor.woolByTier(tier))));
        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumIngot(tier).get(), durationTicks, count, clover, clover,
                Ingredient.of(ModBlocks.getArconiumBlock(tier).get().asItem())));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.BLUE_DYE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.CORNFLOWER), Ingredient.of(Items.BLUE_WOOL), Ingredient.of(Items.BLUE_CONCRETE), Ingredient.of(Items.BLUE_TERRACOTTA)));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.NETHER_WART, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.NETHER_WART), Ingredient.of(Items.RED_NETHER_BRICKS), Ingredient.of(Items.NETHER_WART_BLOCK)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.WITHER_SKELETON_SKULL, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.WITHER_SKELETON_SKULL), Ingredient.of(Items.SOUL_SAND), Ingredient.of(Items.WITHER_ROSE)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.BLAZE_ROD, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.BLAZE_ROD), Ingredient.of(Items.BLAZE_ROD), Ingredient.of(Items.BLAZE_ROD), Ingredient.of(Items.BLAZE_ROD), Ingredient.of(Items.BLAZE_ROD), Ingredient.of(Items.BLAZE_ROD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.DIAMOND, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.DIAMOND_HELMET), Ingredient.of(Items.DIAMOND_CHESTPLATE), Ingredient.of(Items.DIAMOND_LEGGINGS), Ingredient.of(Items.DIAMOND_BOOTS)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.ECHO_SHARD, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.ECHO_SHARD), Ingredient.of(Items.SCULK_SENSOR), Ingredient.of(Items.SCULK_CATALYST), Ingredient.of(Items.BLUE_WOOL), Ingredient.of(Items.DIAMOND_SWORD)));

        previousTier = tier;
        tier = RainbowColor.PURPLE;

        consumer.accept(
                makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier).get(), durationTicks, count, clover, clover,
                        Ingredient.of(ModBlocks.getArconiumTreeSapling(tier).get().asItem()), Ingredient.of(
                                RainbowColor.woolByTier(tier))));
        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumIngot(tier).get(), durationTicks, count, clover, clover,
                Ingredient.of(ModBlocks.getArconiumBlock(tier).get().asItem())));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.PURPLE_DYE, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.RED_DYE), Ingredient.of(Items.BLUE_DYE), Ingredient.of(Items.PURPLE_WOOL), Ingredient.of(Items.PURPLE_CONCRETE), Ingredient.of(Items.PURPLE_TERRACOTTA)));

        consumer.accept(makeEnchantedColoredRoot(tier, Items.NETHER_STAR, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.NETHER_STAR), Ingredient.of(Items.SCULK_SENSOR), Ingredient.of(Items.SCULK_CATALYST), Ingredient.of(Items.PURPLE_WOOL), Ingredient.of(Items.NETHERITE_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.SHULKER_SHELL, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.SHULKER_SHELL), Ingredient.of(Items.PURPLE_SHULKER_BOX), Ingredient.of(Items.NETHERITE_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.GHAST_TEAR, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.GHAST_TEAR), Ingredient.of(Items.END_CRYSTAL), Ingredient.of(Items.NETHERITE_SWORD)));
        consumer.accept(makeEnchantedColoredRoot(tier, Items.ANCIENT_DEBRIS, durationTicks, count, Ingredient.of(ModItems.getArconiumIngot(tier).get()), clover,
                Ingredient.of(Items.ANCIENT_DEBRIS), Ingredient.of(Items.NETHERITE_INGOT), Ingredient.of(Items.NETHERITE_HOE)));
    }

    private void registerArconiumIngotRecipes(Consumer<FinishedRecipe> consumer) {
        Ingredient clover = Ingredient.of(ModItems.fourLeafClover.get());
        RainbowColor color = RainbowColor.RED;
        Ingredient essence = Ingredient.of(ModItems.getArconiumEssence(color).get());

        consumer.accept(
                new PedestalFinishedRecipe(
                        id(color.getTierName() + ItemNames.ARCONIUM_INGOT_SUFFIX),
                        new ItemStack(ModItems.getArconiumIngot(color).get().asItem()),
                        60,
                        Ingredient.of(Items.RED_DYE),
                        Ingredient.of(Items.POPPY),
                        Ingredient.of(Items.RED_WOOL),
                        Ingredient.of(Items.RED_CONCRETE),
                        essence,
                        essence,
                        essence,
                        clover
                )
        );

        color = RainbowColor.ORANGE;
        essence = Ingredient.of(ModItems.getArconiumEssence(color).get());
        consumer.accept(
                new PedestalFinishedRecipe(
                        id(color.getTierName() + ItemNames.ARCONIUM_INGOT_SUFFIX),
                        new ItemStack(ModItems.getArconiumIngot(color).get().asItem()),
                        60,
                        Ingredient.of(Items.ORANGE_DYE),
                        Ingredient.of(Items.RAW_COPPER),
                        Ingredient.of(Items.STRIPPED_ACACIA_LOG),
                        Ingredient.of(Items.PUMPKIN),
                        essence,
                        essence,
                        essence,
                        clover
                )
        );

        color = RainbowColor.YELLOW;
        essence = Ingredient.of(ModItems.getArconiumEssence(color).get());
        consumer.accept(
                new PedestalFinishedRecipe(
                        id(color.getTierName() + ItemNames.ARCONIUM_INGOT_SUFFIX),
                        new ItemStack(ModItems.getArconiumIngot(color).get().asItem()),
                        60,
                        Ingredient.of(Items.RAW_GOLD),
                        Ingredient.of(Items.DANDELION),
                        Ingredient.of(Items.YELLOW_CONCRETE),
                        Ingredient.of(Items.HAY_BLOCK),
                        essence,
                        essence,
                        essence,
                        clover
                )
        );

        color = RainbowColor.GREEN;
        essence = Ingredient.of(ModItems.getArconiumEssence(color).get());
        consumer.accept(
                new PedestalFinishedRecipe(
                        id(color.getTierName() + ItemNames.ARCONIUM_INGOT_SUFFIX),
                        new ItemStack(ModItems.getArconiumIngot(color).get().asItem()),
                        60,
                        Ingredient.of(Items.EMERALD),
                        Ingredient.of(Items.EMERALD),
                        Ingredient.of(Items.WAXED_WEATHERED_COPPER),
                        Ingredient.of(Items.MELON),
                        essence,
                        essence,
                        essence,
                        clover
                )
        );

        color = RainbowColor.LIGHT_BLUE;
        essence = Ingredient.of(ModItems.getArconiumEssence(color).get());
        consumer.accept(
                new PedestalFinishedRecipe(
                        id(color.getTierName() + ItemNames.ARCONIUM_INGOT_SUFFIX),
                        new ItemStack(ModItems.getArconiumIngot(color).get().asItem()),
                        60,
                        Ingredient.of(Items.DIAMOND),
                        Ingredient.of(Items.DIAMOND),
                        Ingredient.of(Items.OBSIDIAN),
                        Ingredient.of(Items.BLUE_ICE),
                        essence,
                        essence,
                        essence,
                        clover
                )
        );

        color = RainbowColor.BLUE;
        essence = Ingredient.of(ModItems.getArconiumEssence(color).get());
        consumer.accept(
                new PedestalFinishedRecipe(
                        id(color.getTierName() + ItemNames.ARCONIUM_INGOT_SUFFIX),
                        new ItemStack(ModItems.getArconiumIngot(color).get().asItem()),
                        60,
                        Ingredient.of(Items.WARPED_NYLIUM),
                        Ingredient.of(Items.PRISMARINE),
                        Ingredient.of(Items.NETHERITE_SCRAP),
                        Ingredient.of(Items.BLAZE_ROD),
                        essence,
                        essence,
                        essence,
                        clover
                )
        );

        color = RainbowColor.PURPLE;
        essence = Ingredient.of(ModItems.getArconiumEssence(color).get());
        consumer.accept(
                new PedestalFinishedRecipe(
                        id(color.getTierName() + ItemNames.ARCONIUM_INGOT_SUFFIX),
                        new ItemStack(ModItems.getArconiumIngot(color).get().asItem()),
                        60,
                        Ingredient.of(Items.SHULKER_SHELL),
                        Ingredient.of(Items.DRAGON_BREATH),
                        Ingredient.of(Items.PURPUR_BLOCK),
                        Ingredient.of(Items.END_ROD),
                        essence,
                        essence,
                        essence,
                        clover
                )
        );

    }

    private void registerMisc(Consumer<FinishedRecipe> consumer) {
        consumer.accept(
                new PedestalFinishedRecipe(
                        id(ItemNames.GOLD_COIN),
                        new ItemStack(ModItems.goldCoin.get().asItem()),
                        200, // TODO set back to 20, or remove recipe
                        Ingredient.of(Items.GOLD_NUGGET)
                )
        );
    }

    private void registerInfiniteGoldArconiumBlocks(Consumer<FinishedRecipe> consumer) {
        RainbowColor.stream().forEach(color -> consumer.accept(makeInfiniteGoldArconiumBlock(color)));
    }

    private static FinishedRecipe makeInfiniteGoldArconiumBlock(RainbowColor color) {
        ItemStack output = new ItemStack(ModBlocks.getInfiniteGoldArconiumBlock(color).get().asItem());
        Ingredient goldBlock = Ingredient.of(Blocks.GOLD_BLOCK.asItem());
        if (color != RainbowColor.RED) {
            goldBlock = Ingredient.of(ModBlocks.getInfiniteGoldArconiumBlock(color.getPreviousTier()).get().asItem());
        }
        Ingredient sapling = Ingredient.of(ModBlocks.getArconiumTreeSapling(color).get().asItem());
        Ingredient clover = Ingredient.of(ModItems.fourLeafClover.get());
        Ingredient dye = Ingredient.of(RainbowColor.dyeByTier(color));
        Item extraItem = RainbowColor.dyeByTier(color);
        switch(color) {
            case YELLOW: extraItem = Items.YELLOW_CANDLE; break;
            case GREEN: extraItem = Items.EMERALD_BLOCK; break;
            case LIGHT_BLUE: extraItem = Items.BLUE_ICE; break;
            case BLUE: extraItem = Items.TUBE_CORAL_BLOCK; break;
            case PURPLE: extraItem = Items.PURPLE_SHULKER_BOX; break;
        }
        ResourceLocation recipeId = id(color.getTierName() + BlockNames.INFINITE_GOLD_ARCONIUM_BLOCK_SUFFIX);
        final int durationTicks = 100;
        return new PedestalFinishedRecipe(recipeId, output, durationTicks, goldBlock, sapling, dye, dye, dye, Ingredient.of(extraItem), clover, clover);
    }


    /**
     * Craft an enchanted colored root for a given item to be generated as part of the resource generation of the mod
     *
     * @param tier             Tier of colored root to make
     * @param resourceItem     The item to be produced by the tree
     * @param durationTicks    time the crafting recipe will take to make the root
     * @param resourceGenCount Number of items to generate per resource generation event
     * @param ingredients
     * @return
     */
    private static FinishedRecipe makeEnchantedColoredRoot(
            RainbowColor tier, ItemLike resourceItem, int durationTicks, int resourceGenCount, Ingredient... ingredients) {
        Item root = ModItems.getColoredRoot(tier).get();
        ItemStack coloredRoot = new ItemStack(root);
        ColoredRoot.setResourceItem(coloredRoot, resourceItem, resourceGenCount);
        ResourceLocation rootId = Registry.ITEM.getKey(root);
        ResourceLocation itemId = Registry.ITEM.getKey(resourceItem.asItem());
        ResourceLocation recipeId = id(rootId.getPath() + "/" + itemId.getNamespace() + "_" + itemId.getPath());
        Arconia.logger.info("***** Recipe ID: " + recipeId);
        Ingredient[] newIngredients = Arrays.copyOf(ingredients, ingredients.length + 1);
        newIngredients[ingredients.length] = Ingredient.of(root);
        return new PedestalFinishedRecipe(recipeId, coloredRoot, durationTicks, newIngredients);
    }

    private static ResourceLocation id(String s) {
        return new ResourceLocation(Arconia.MOD_ID, "pedestal/" + s);
    }


    private static class PedestalFinishedRecipe implements FinishedRecipe {
        private final ResourceLocation id;
        private final ItemStack output;
        private final Ingredient[] inputs;
        private final int durationTicks;

        private PedestalFinishedRecipe(ResourceLocation id, ItemStack output, int durationTicks, Ingredient... inputs) {
            this.id = id;
            this.output = output;
            this.durationTicks = durationTicks;
            this.inputs = inputs;
        }

        @Override
        public void serializeRecipeData(JsonObject json) {
            json.add("output", serializeStack(output));
            json.add("durationTicks", new JsonPrimitive(durationTicks));
            JsonArray ingredients = new JsonArray();
            for (Ingredient ingredient : inputs) {
                ingredients.add(ingredient.toJson());
            }
            json.add("ingredients", ingredients);
        }

        private static JsonObject serializeStack(ItemStack stack) {
            CompoundTag nbt = stack.save(new CompoundTag());
            byte c = nbt.getByte("Count");
            if (c != 1) {
                nbt.putByte("count", c);
            }
            nbt.remove("Count");
            renameTag(nbt, "id", "item");
            renameTag(nbt, "tag", "nbt");
            Dynamic<Tag> dyn = new Dynamic<>(NbtOps.INSTANCE, nbt);
            return dyn.convert(JsonOps.INSTANCE).getValue().getAsJsonObject();
        }

        private static void renameTag(CompoundTag nbt, String oldName, String newName) {
            Tag tag = nbt.get(oldName);
            if (tag != null) {
                nbt.remove(oldName);
                nbt.put(newName, tag);
            }
        }


        @Override
        public ResourceLocation getId() {
            return id;
        }

        @Override
        public RecipeSerializer<?> getType() {
            return ModRecipeTypes.PEDESTAL_SERIALIZER.get();
        }

        @Nullable
        @Override
        public JsonObject serializeAdvancement() {
            return null;
        }

        @Nullable
        @Override
        public ResourceLocation getAdvancementId() {
            return null;
        }
    }
}