package lonestarrr.arconia.data.recipes;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import com.mojang.serialization.Dynamic;
import com.mojang.serialization.JsonOps;
import lonestarrr.arconia.common.Arconia;
import lonestarrr.arconia.common.block.ModBlocks;
import lonestarrr.arconia.common.core.BlockNames;
import lonestarrr.arconia.common.core.RainbowColor;
import lonestarrr.arconia.common.crafting.ModRecipeTypes;
import lonestarrr.arconia.common.item.ColoredRoot;
import lonestarrr.arconia.common.item.ModItems;
import net.minecraft.core.Registry;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.recipes.FinishedRecipe;
import net.minecraft.data.recipes.RecipeProvider;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.NbtOps;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Blocks;

import javax.annotation.Nullable;
import java.util.Arrays;
import java.util.function.Consumer;

/**
 * Registers recipes specific for the pedestal crafting ritual
 */
public class PedestalProvider extends RecipeProvider {

    public PedestalProvider(DataGenerator gen) {
        super(gen);
    }

    @Override
    public String getName() {
        return "Arconia pedestal recipes";
    }

    @Override
    protected void buildCraftingRecipes(Consumer<FinishedRecipe> consumer) {
        registerColoredRootRecipes(consumer);
        registerGoldArconiumBlocks(consumer);
        // TODO have yet to implement visually different rendering based on it having infinite turned on
        registerInfiniteGoldArconiumBlocks(consumer);
    }

    /*
     * Recipes for colored roots with nbt data on them indicating what item will be generated by the mod's resource generator
     */
    private void registerColoredRootRecipes(Consumer<FinishedRecipe> consumer) {
        final Ingredient clover = Ingredient.of(ModItems.fourLeafClover);

        int durationTicks = 200; // Time for ritual to create the item from the recipe
        int interval = 10; // Resource Generation - minimum interval, in resource generator events, between resource generation
        int count = 1; // Number of items to generate per resource generation event
        int cost = 1; // Number of coins the resource generated should cost
        RainbowColor tier = RainbowColor.RED;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, clover, clover, Ingredient.of(Items.RED_WOOL)));
        for (Item item: new Item[] { Items.OAK_LOG, Items.DARK_OAK_LOG, Items.BIRCH_LOG, Items.JUNGLE_LOG, Items.ACACIA_LOG, Items.SPRUCE_LOG, Items.SAND, Items.GRAVEL, Items.DIRT, Items.KELP }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }

        RainbowColor previousTier = tier;
        tier = RainbowColor.ORANGE;
        durationTicks = 200;
        interval = 9;
        cost = 2;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(previousTier)), clover, Ingredient.of(Items.ORANGE_WOOL)));
        for (Item item: new Item[] { Items.ORANGE_DYE, Items.COAL, Items.STONE, Items.DIORITE, Items.GRANITE, Items.ANDESITE, Items.STRING, Items.COOKED_BEEF, Items.SUGAR_CANE }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }

        previousTier = tier;
        tier = RainbowColor.YELLOW;
        durationTicks = 400;
        interval = 8;
        cost = 4;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(previousTier)), clover, Ingredient.of(Items.YELLOW_WOOL)));
        for (Item item: new Item[] { Items.YELLOW_DYE, Items.IRON_INGOT, Items.ARROW, Items.LEATHER, Items.COOKED_PORKCHOP }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }

        previousTier = tier;
        tier = RainbowColor.GREEN;
        durationTicks = 400;
        interval = 7;
        cost = 8;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(previousTier)), clover, Ingredient.of(Items.GREEN_WOOL)));
        for (Item item: new Item[] { Items.GREEN_DYE, Items.GOLD_INGOT, Items.LAPIS_LAZULI, Items.REDSTONE, Items.GUNPOWDER }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }

        previousTier = tier;
        tier = RainbowColor.LIGHT_BLUE;
        durationTicks = 400;
        interval = 6;
        cost = 16;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(previousTier)), clover, Ingredient.of(Items.LIGHT_BLUE_WOOL)));
        for (Item item: new Item[] { Items.LIGHT_BLUE_DYE, Items.DIAMOND, Items.OBSIDIAN, Items.ENDER_PEARL }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }

        previousTier = tier;
        tier = RainbowColor.BLUE;
        durationTicks = 400;
        interval = 5;
        cost = 32;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(previousTier)), clover, Ingredient.of(Items.BLUE_WOOL)));
        for (Item item: new Item[] { Items.BLUE_DYE, Items.NETHERRACK, Items.SOUL_SAND, Items.SOUL_SOIL, Items.BLAZE_ROD, Items.WARPED_STEM, Items.EMERALD, Items.NETHER_WART }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }

        previousTier = tier;
        tier = RainbowColor.PURPLE;
        durationTicks = 800;
        interval = 4;
        cost = 64;

        consumer.accept(makeEnchantedColoredRoot(tier, ModItems.getArconiumEssence(tier), durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(previousTier)), clover, Ingredient.of(Items.PURPLE_WOOL)));
        for (Item item: new Item[] { Items.PURPLE_DYE, Items.END_STONE, Items.CHORUS_FRUIT, Items.GHAST_TEAR, Items.SHULKER_SHELL }) {
            consumer.accept(makeEnchantedColoredRoot(tier, item, durationTicks, interval, count, cost, Ingredient.of(ModItems.getArconiumIngot(tier)), clover, Ingredient.of(item)));
        }
    }

    private void registerGoldArconiumBlocks(Consumer<FinishedRecipe> consumer) {
        RainbowColor.stream().forEach(color -> consumer.accept(makeGoldArconiumBlock(color)));
    }

    private void registerInfiniteGoldArconiumBlocks(Consumer<FinishedRecipe> consumer) {
        RainbowColor.stream().forEach(color -> consumer.accept(makeInfiniteGoldArconiumBlock(color)));
    }

    private static FinishedRecipe makeGoldArconiumBlock(RainbowColor color) {
        ItemStack output = new ItemStack(ModBlocks.getGoldArconiumBlock(color).asItem());
        Ingredient goldBlock = Ingredient.of(Blocks.GOLD_BLOCK.asItem());
        Ingredient essence = Ingredient.of(ModItems.getArconiumEssence(color));
        ResourceLocation recipeId = id(color.getTierName() + BlockNames.GOLD_ARCONIUM_BLOCK_SUFFIX);
        final int durationTicks = 100 + (color.getTier() * 100);
        return new PedestalFinishedRecipe(recipeId, output, durationTicks, goldBlock, essence, essence, essence, essence, essence, essence);
    }

    private static FinishedRecipe makeInfiniteGoldArconiumBlock(RainbowColor color) {
        ItemStack output = new ItemStack(ModBlocks.getInfiniteGoldArconiumBlock(color).asItem());
        Ingredient goldArconiumBlock = Ingredient.of(ModBlocks.getGoldArconiumBlock(color).asItem());
        Ingredient arconiumBlock = Ingredient.of(ModBlocks.getArconiumBlock(color).asItem());
        ResourceLocation recipeId = id(color.getTierName() + BlockNames.INFINITE_GOLD_ARCONIUM_BLOCK_SUFFIX);
        final int durationTicks = 100 + (color.getTier() * 100);
        return new PedestalFinishedRecipe(recipeId, output, durationTicks, goldArconiumBlock, arconiumBlock, arconiumBlock, arconiumBlock, arconiumBlock, arconiumBlock, arconiumBlock, arconiumBlock);
    }


    /**
     * Craft an enchanted colored root for a given item to be generated as part of the resource generation of the mod
     *
     * @param tier Tier of colored root to make
     * @param resourceItem The item to be produced by the tree
     * @param durationTicks time the crafting recipe will take to make the root
     * @param resourceGenCount Number of items to generate per resource generation event
     * @param resourceGenInterval Frequency with which resource is generated. An interval of 1 is fastest. Interval length is determined by the pot of gold and is typically no less than 5 ticks.
     * @param resourceCoinCost How many coins it costs to generate this resource
     * @param ingredients
     * @return
     */
    private static FinishedRecipe makeEnchantedColoredRoot(RainbowColor tier, ItemLike resourceItem, int durationTicks, int resourceGenInterval, int resourceGenCount, int resourceCoinCost, Ingredient... ingredients) {
        Item root = ModItems.getColoredRoot(tier);
        ItemStack coloredRoot = new ItemStack(root);
        ColoredRoot.setResourceItem(coloredRoot, resourceItem, resourceGenInterval, resourceGenCount, resourceCoinCost);
        ResourceLocation rootId = Registry.ITEM.getKey(root);
        ResourceLocation itemId = Registry.ITEM.getKey(resourceItem.asItem());
        ResourceLocation recipeId = id(rootId.getPath() + "/" + itemId.getNamespace() + "_" + itemId.getPath());
        Arconia.logger.info("***** Recipe ID: " + recipeId);
        Ingredient[] newIngredients = Arrays.copyOf(ingredients, ingredients.length + 1);
        newIngredients[ingredients.length] = Ingredient.of(root);
        return new PedestalFinishedRecipe(recipeId, coloredRoot, durationTicks, newIngredients);
    }

    private static ResourceLocation id(String s) {
        return new ResourceLocation(Arconia.MOD_ID, "pedestal/" + s);
    }


    private static class PedestalFinishedRecipe implements FinishedRecipe {
        private final ResourceLocation id;
        private final ItemStack output;
        private final Ingredient[] inputs;
        private final int durationTicks;

        private PedestalFinishedRecipe(ResourceLocation id, ItemStack output, int durationTicks, Ingredient... inputs) {
            this.id = id;
            this.output = output;
            this.durationTicks = durationTicks;
            this.inputs = inputs;
        }

        @Override
        public void serializeRecipeData(JsonObject json) {
            json.add("output", serializeStack(output));
            json.add("durationTicks", new JsonPrimitive(durationTicks));
            JsonArray ingredients = new JsonArray();
            for (Ingredient ingredient : inputs) {
                ingredients.add(ingredient.toJson());
            }
            json.add("ingredients", ingredients);
        }

        private static JsonObject serializeStack(ItemStack stack) {
            CompoundTag nbt = stack.save(new CompoundTag());
            byte c = nbt.getByte("Count");
            if (c != 1) {
                nbt.putByte("count", c);
            }
            nbt.remove("Count");
            renameTag(nbt, "id", "item");
            renameTag(nbt, "tag", "nbt");
            Dynamic<Tag> dyn = new Dynamic<>(NbtOps.INSTANCE, nbt);
            return dyn.convert(JsonOps.INSTANCE).getValue().getAsJsonObject();
        }

        private static void renameTag(CompoundTag nbt, String oldName, String newName) {
            Tag tag = nbt.get(oldName);
            if (tag != null) {
                nbt.remove(oldName);
                nbt.put(newName, tag);
            }
        }

        @Override
        public ResourceLocation getId() {
            return id;
        }

        @Override
        public RecipeSerializer<?> getType() {
            return ModRecipeTypes.PEDESTAL_SERIALIZER;
        }

        @Nullable
        @Override
        public JsonObject serializeAdvancement() {
            return null;
        }

        @Nullable
        @Override
        public ResourceLocation getAdvancementId() {
            return null;
        }
    }
}